# Generated by Django 5.1.1 on 2024-11-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0005_empleado_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_peso',
            field=models.CharField(blank=True, choices=[('KG', 'Kilogramos'), ('GR', 'Gramos')], default='KG', max_length=2, null=True, verbose_name='Unidad de Peso'),
        ),
    ]
