# Generated by Django 5.1.1 on 2024-11-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0007_historialprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='precio_nuevo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
