# Generated by Django 5.1.1 on 2024-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0008_alter_historialprecio_precio_nuevo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='tipo_cambio',
            field=models.CharField(choices=[('AUMENTO', 'Aumento de Precio'), ('DESCUENTO', 'Descuento'), ('OFERTA', 'Oferta Temporal')], max_length=15),
        ),
    ]
