# Generated by Django 5.1.1 on 2024-11-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0009_alter_historialprecio_tipo_cambio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialprecio',
            options={'ordering': ['-fecha_inicio']},
        ),
    ]
