# Generated by Django 5.1.1 on 2024-11-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0010_alter_historialprecio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsaabierta',
            name='total_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
