# Generated by Django 5.0.6 on 2024-11-24 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0012_tarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fyh_creacion'], 'permissions': [('asignar_tareas', 'Puede asignar tareas específicas'), ('eliminar_cualquier_tarea', 'Puede eliminar cualquier tarea'), ('ver_todas_tareas', 'Puede ver todas las tareas')]},
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='es_tarea_especifica',
            field=models.BooleanField(default=False),
        ),
    ]
