# Generated by Django 5.1.1 on 2024-11-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0013_alter_tarea_options_tarea_asignado_a_tarea_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='intentos_desmarcar',
            field=models.IntegerField(default=0),
        ),
    ]
