# Generated by Django 5.0.6 on 2024-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0014_tarea_intentos_desmarcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsaabierta',
            name='motivo_cierre_especial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
